### ISSUE TITLE
Missing header

### ISSUE THREAD

**Issue by briandgregory** [ylmrx/snh#1]
I attempted to build this and resulted in the following:

>> Installing /workspace/drumlogue/snh
Compiling header.c
Compiling _unit_base.c
Compiling unit.cc
In file included from unit.cc:10:0:
delay.h:19:24: fatal error: maximilian.h: No such file or directory

**Comment by ylmrx** [comment]
Yes you need to have the Maximilian lib sources in your tree, as described here : https://github.com/ylmrx/maxisynthsvf?tab=readme-ov-file#how-to-build

Bear in mind if you don't intend to code or tweak the fx, there's a pre-built drmlgunit at the root of the repo you can just copy to your drumlogue so you don't need to bother with building it.

I'll add the deps section to the readme here too.

**Comment by briandgregory** [comment]
Thanks, yes, I figured that out right after I sent these. Sorry for the
noise.
By the way, are you familiar with the reverb components in the Maximilian
lib? There seems to be little to no documentation on these.

-Brian

**Comment by ylmrx** [comment]
I wasn't aware of it. It's good to know but it's freeverb, so likely not much better (and certainly not as optimized) than the native one. 
I'll give it a try when I get the time. :)
